SELECT CONCAT(ROUTINE_SCHEMA, '.', ROUTINE_NAME)                                                        as entity_name,
       ROUTINE_NAME                                                                                     as entity_name_short,
       CONCAT('mysql.', REPLACE((SELECT @@hostname), '.', '-'), '.', ROUTINE_SCHEMA, '.', ROUTINE_NAME) as urn,
       CONCAT('mysql.', REPLACE((SELECT @@hostname), '.', '-'), '.', ROUTINE_SCHEMA)                    as parent_urn,
       (SELECT @@hostname)                                                                              as hostname,
       JSON_OBJECT('core_system', 'MySQL',
                   'procedure_schema', ROUTINE_SCHEMA,
                   'procedure_name', ROUTINE_NAME,
                   'procedure_type', ROUTINE_TYPE,
                   'procedure_language', ROUTINE_BODY,
                   'procedure_code', ROUTINE_DEFINITION,
                   'create_time', CREATED,
                   'update_time', LAST_ALTERED,
                   'procedure_comment', IF(ROUTINE_COMMENT = '', NULL, ROUTINE_COMMENT))                as json_data,
       JSON_OBJECT('CORE_SYSTEM', 'MySQL',
                   'PROCEDURE_LANGUAGE', ROUTINE_BODY,
                   'CREATE_TIME', CREATED,
                   'UPDATE_TIME', LAST_ALTERED)                                                         as json_data_ui,
       IF(ROUTINE_COMMENT = '', NULL, JSON_OBJECT('notifications',
                                                  JSON_ARRAY(JSON_OBJECT('title', 'Procedure comment',
                                                                         'type', 'info',
                                                                         'body',
                                                                         ROUTINE_COMMENT))))            as notifications,
       JSON_OBJECT('codes',
                   JSON_ARRAY(JSON_OBJECT('code_name', 'Procedure definition',
                                          'code_language', ROUTINE_BODY,
                                          'highlight', TRUE,
                                          'code_block', ROUTINE_DEFINITION)))                           as codes
FROM information_schema.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE'
  and ROUTINE_SCHEMA = '{{ params.schema }}';