INSERT INTO dds.entity (loaded_by_eid, entity_type_etid, entity_name, entity_name_short, urn, parent_eid, info,
                        search_data, json_data, json_data_ui, codes, htmls, links, notifications, tables, tags)
VALUES (NULL,
        (SELECT etid FROM dds.entity_types WHERE entity_type_name = 'etl' LIMIT 1),
        'datacatalog.{{ params.exporter_name }}',
        '{{ params.exporter_name }}',
        'datacatalog.airflow.etl.{{ params.exporter_name }}',
        NULL,
        '{{ params.source_name }} metadata exporter for data catalog',
        'metadata exporter',
        '{"core_system": "Airflow"}',
        '{"CORE_SYSTEM": "Airflow"}',
        NULL, NULL, NULL, NULL, NULL,
        '{"Airflow", "{{ params.source_name }}", "exporter", "ETL"}')
  ON CONFLICT (urn) DO UPDATE SET loaded_by_eid     = NULL,
                          entity_type_etid  = (SELECT etid FROM dds.entity_types WHERE entity_type_name = 'etl' LIMIT 1),
                          entity_name       = '{{ params.exporter_name }}',
                          entity_name_short = '{{ params.exporter_name }}',
                          parent_eid        = NULL,
                          info              = '{{ params.source_name }} metadata exporter for data catalog',
                          search_data       = 'mysql-metadata-exporter',
                          json_data         = '{"core_system": "Airflow"}',
                          json_data_ui      = '{"CORE_SYSTEM": "Airflow"}',
                          codes             = NULL,
                          htmls             = NULL,
                          links             = NULL,
                          notifications     = NULL,
                          tables            = NULL,
                          tags              = '{"Airflow", "{{ params.source_name }}", "exporter", "ETL"}'
WHERE dds.entity.urn = 'datacatalog.airflow.etl.{{ params.exporter_name }}';