INSERT INTO dds.entity (loaded_by_eid, entity_type_etid, entity_name, entity_name_short, urn, parent_eid, info,
                        search_data, json_data, json_data_ui, codes, htmls, links, notifications, tables, tags)
VALUES ((SELECT eid FROM dds.entity WHERE dds.entity.urn = 'datacatalog.airflow.etl.{{ params.exporter_name }}' LIMIT 1),
        (SELECT etid FROM  dds.entity_types WHERE entity_type_name = 'table' LIMIT 1),
        '{{ params.entity_name }}',
        '{{ params.entity_name_short }}',
        '{{ params.urn }}',
        (SELECT eid FROM dds.entity WHERE dds.entity.urn = '{{ params.parent_urn }}' LIMIT 1),
        'Table at {{ params.source_name }} {{ params.hostname }} instance',
        '{{ params.entity_name_short }}',
        '{{ params.json_data }}',
        '{{ params.json_data_ui }}',
        NULL, NULL, NULL,
        NULLIF('{{ params.notifications }}'::jsonb, '{"None": "None"}'::jsonb),
        '{{ params.tables }}',
        '{"{{ params.source_name }}", "table"}')
  ON CONFLICT (urn)  DO UPDATE SET loaded_by_eid = (SELECT eid FROM dds.entity WHERE dds.entity.urn = 'datacatalog.airflow.etl.{{ params.exporter_name }}' LIMIT 1),
                          entity_type_etid = (SELECT etid FROM  dds.entity_types WHERE entity_type_name = 'table' LIMIT 1),
                          entity_name = '{{ params.entity_name }}',
                          entity_name_short = '{{ params.entity_name_short }}',
                          parent_eid = (SELECT eid FROM dds.entity WHERE dds.entity.urn = '{{ params.parent_urn }}' LIMIT 1),
                          info = 'Table at {{ params.source_name }} {{ params.hostname }} instance',
                          search_data = '{{ params.entity_name_short }}',
                          json_data = '{{ params.json_data }}',
                          json_data_ui = '{{ params.json_data_ui }}',
                          codes = NULL,
                          htmls = NULL,
                          links = NULL,
                          notifications = NULLIF('{{ params.notifications }}'::jsonb, '{"None": "None"}'::jsonb),
                          tables = '{{ params.tables }}',
                          tags = '{"{{ params.source_name }}", "table"}'
WHERE dds.entity.urn = '{{ params.urn }}';